RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
SCORE_THRESHOLD : 0.6
CHUNK_SIZE: 500
CHUNK_OVERLAP: 50
DATA_PATH: 'data/'
DB_FAISS_PATH: 'vectorstore/db_faiss'
# MODEL_TYPE: 'mpt'
# MODEL_BIN_PATH: 'models/mpt-7b-instruct.ggmlv3.q8_0.bin'
MODEL_TYPE: 'llama'
MODEL_BIN_PATH: 'models/llama-2-13b-chat.ggmlv3.q8_0.bin'
MODEL_SENT_TOKENIZER : 'sentence-transformers/all-MiniLM-L6-v2' #gtr-t5-xxl
MAX_NEW_TOKENS: 256
TEMPERATURE: 0.01